# Generated by Django 4.2.7 on 2023-11-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_category_options_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='item_images'),
        ),
    ]
